config/routes.rb
Rails.application.routes.draw do

  root 'dog#index'

  get 'murphy' => 'dog#murphy'
  get 'wylee' => 'dog#wylee'
  get 'boon' => 'dog#boon'
  get 'kaya' => 'dog#kaya'
  get 'boomer' => 'dog#boomer'
  get 'shaka' => 'dog#shaka'
  get 'trooper' => 'dog#trooper'
  get 'tucker' => 'dog#tucker'
  get 'all_dogs' => 'dog#all_dogs'
  get 'avi' => "avi#avi"
  get 'press' => "avi#press"
  get 'donate' => "avi#donate"
  get 'about' => "avi#about"
  get 'contact' => "avi#contact"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  before_save { self.name = name.downcase }
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true
  validates :email,  format: { with: EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  has_secure_password
end

app/models/dog.rb
class Dog < ActiveRecord::Base
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

def index

end


end

app/controllers/avi_controller.rb
class AviController < ApplicationController

  def avi
  end

  def press
  end

  def donate
  end

  def contact
  end

  def about
  end

end

app/controllers/dog_controller.rb
class DogController < ApplicationController

  def index
  end

  def show
  end

  def edit
  end

  def delete
  end

  def new
  end

  def create
  end

  def all_dogs
  end


  def murphy
    @name = "Murphy"
    @img = 'murphy_crop.png'
    @breed = "Golden Retreiver"
    @sex = "male"
    birthday = "28/11/2006"
    @weight = "75"
    @age = age(birthday)
    dob = Date.new(2006, 11, 28)
    @DOB = dob.to_formatted_s(:long_ordinal)
    @handler = "Eric Seelenfreund"
    @handler_img = 'ziggy.png'

    @years_on_patrol = "20"
    @full_name = "Eric Seelenfreund"
    @occupation = ["Ski Patrol", "Property Maintenance"]
    @interests = ["Skiing", "Mountain Biking", "Mountaineering", "Kayaking", "Surfing"]

  end

  def boomer
    @name = "Boomer"
    @img = 'boomer_card.jpg'
    @breed = "Golden Retreiver"
    @sex = "male"
    birthday = "06/03/2011"
    @weight = "85"
    @age = age(birthday)
    dob = Date.new(2011, 3, 6)
    @DOB = dob.to_formatted_s(:long_ordinal)
    @handler = "Will Paden"
    @handler_img = "will.png"
  end

  def kaya
    @name = "Kaya"
    @img = 'kaya_card.jpg'
    @breed = "Belgian Malinois"
    @sex = "female"
    birthday = "05/09/10"
    @weight = "50"
    @age = age(birthday)
    dob = Date.new(2010, 9, 5)
    @DOB = dob.to_formatted_s(:long_ordinal)
    @handler = "Ben Stone"
    @handler_img ="ben.png"
  end

  def shaka
    @name = "Shaka"
    @img = "shaka_card.jpg"
    @breed = "Golden Retreiver"
    @sex = "male"
    @DOB = ""
    @weight = "40"
    @age = "1"
     @handler = "Ivan McGurk"
    @handler_img = "ivan.png"
  end


def tucker
    @name = "Tucker"
    @img = 'tucker_card.jpg'
    @breed = "Golden Retreiver"
    @sex = "male"
    birthday = "20/06/2003"
    @weight = "65"
    @age = age(birthday)
    dob = Date.new(2003, 6, 20)
    @DOB = dob.to_formatted_s(:long_ordinal)
    @handler = "Peter York"
    @handler_img = 'pete.png'
  end

def wylee
    @name = "Wylee"
    @img = 'wylee_card_crop.jpg'
    @breed = "Boarder Collie"
    @sex = "male"
    birthday = "12/06/2007"
    @weight = "45"
    @age = age(birthday)
    dob = Date.new(2007, 6, 12)
    @DOB = dob.to_formatted_s(:long_ordinal)
    @handler = "Craig Noble"
    @handler_img = "craig.png"
end

def boon
    @name = "Boon"
    @img = 'boon_card.jpg'
    @breed = "German Shepard"
    @sex = "female"
    birthday = "23/08/2003"
    @weight = "65"
    @age = age(birthday)
    dob = Date.new(2003, 8, 23)
    @DOB = dob.to_formatted_s(:long_ordinal)
    @handler = "Erik Knudson"
    @handler_img = 'erik.png'
  end


  def trooper
    @name = "Trooper"
    @img = 'trooper_card.jpg'
    @breed = "Labrador Retreiver"
    @sex = "male"
    birthday = "21/12/2015"
    dob = Date.new(2015, 12, 21)
    @DOB = dob.to_formatted_s(:long_ordinal)
    @weight = "30"
    @age = age(birthday)
    @handler = "Steve Selander"
    @handler_img = "steve.png"
  end

private
  def age dob

    return nil unless dob.present?

    birthday = DateTime.parse(dob).to_date
    today = Time.current.to_date
    if today.month < birthday.month || (today.month == birthday.month && birthday.day > today.day)
    today.year - birthday.year - 1
    else
    today.year - birthday.year
    end


  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/dog_helper.rb
module DogHelper

   def embed(youtube_url)
    youtube_id = youtube_url.split("=").last
    content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
    end

end

app/views/avi/about.html.erb
<%= render 'layouts/header' %>
<div class= "container">
<div class="jumbotron">
  This site was designed for the Squaw Valley Ski Patrol Dog Program. With special thanks to @joshhunt for his codepen <a href="http://codepen.io/joshhunt/pen/LVQZRa" class="thanks">Pure CSS Netflix Video Carousel</a> and Adobe Web Platform for the pen <a href="http://codepen.io/adobe/pen/d056d1b26b9683c018f9bb9e0f1b0e1c" class="thanks">Frosted Glass Effect Using Filter Effects</a>
</div>
</div>
<%= render 'layouts/footer' %>

app/views/avi/avi.html.erb
<%= render "layouts/header" %>
<div class="container-fluid">
   <div class="avi_events_container"><h4 class="events">Current Events</h4><small class="caption">  <h5 class="event_heading">Free Transceiver workshops<br /></h5>
                <p class="Body">   <span style="line-height: 18px; " class="style_2"> Starting Dec 15th, these free clinics run through the winter on the 1st and 15th of each month through April. <br /></span></p>
                <p style="padding-bottom: 0pt; " class="Body"><span style="line-height: 18px; " class="style_2">Call 530-581-7260 for details.</span></p></small></div>
  <h1 class="fund">Squaw Valley Avalanche Education Fund</h1>

<div class="avi_img_container left"><%= image_tag "boomer_avi.jpg", class: "avi_img img-responsive" %><small class="caption">Boomer stands guard atop KT</small></div>

<p class="avi">Squawdogs is currently managing the Squaw Valley Avalanche Education Fund.  This fund is dedicated to the education of the general public in Avalanche Education.  We will be working hard to keep the mission of educating the community a top priority.<br /></p>

                <p class="avi">In the last ten years, this fund has awarded well over 140 Avalanche Level 1 scholarships to members of the community  <br /></p>

                <p class="avi">Since 1995, we have been offering a free two hour avalanche awareness and transceiver clinic every friday night during the winter months.  From its inception, we estimate that we have reached out to well over 4,500 members of our community.<br /></p>
                <div class="avi_link_container right"><small class="caption">Resources and Useful Links:</small>
                  <%= link_to "http://sierraavalanchecenter.org/" do %><%= image_tag "Sierra_avi.jpg", class: "avi_img img-responsive" %><% end %><%= link_to "http://avtraining.org/" do %><%= image_tag "aiare.jpg", class: "avi_img img-responsive" %><% end %><%= link_to "http://www.recco.com/" do %><%= image_tag "RECCO_logo.svg.png", class: "avi_img img-responsive" %><% end %></div>

                <p class="avi">Since the late 1980s, we have been hosting the “Steep &amp; Deep Clinic”.  An entertaining night of avalanche education with presentations by local legends, guides, sponsored athletes, and avalanche professionals.  <br /></p>
                <p class="avi">Attended by all ages, this event has touched over 4,000 members of our community.   <br /></p>

                <p style="padding-bottom: 0pt; " class="avi">Please check back for updates on current educational opportunities and events we are offering.</p>
              </div>
              <%= render "layouts/footer" %>

app/views/avi/contact.html.erb
<%= render 'layouts/header' %>
<div class= "container">
<div class="jumbotron">
  This site was designed for the Squaw Valley Ski Patrol Dog Program. Contact the site administrator if you are having problems.
</div>
</div>
<%= render 'layouts/footer' %>

app/views/avi/donate.html.erb
<%= render "layouts/header" %>
<div class="trooper_image">
<%= image_tag "media_meet-trooper.jpg", class:"img-responsive", id: "trooper-donate"
 %>
 <span>Donate</span>
</div>

 <div class="container">
                <h4 style="padding-top: 0pt; " >Squawdogs appreciates your support. <br /></h4>
                <p class="Bod"><br /></p>
                <p class="Bod">Please find the information below<br /></p>
                <p class="paragraph_style_1"><br /></p>
                <p class="paragraph_style_1"><span style="line-height: 18px; " class="style">Squaw Valley Avalanche Rescue Dog &amp; Education Fund</span><br /></p>
                <p class="paragraph_style_1"><span style="line-height: 18px; " class="style">Non-Profit 501(c)(3)  27-1117627<br /></span></p>
                <p class="paragraph_style_1"><span style="line-height: 18px; " class="style"><br /></span></p>
                <p class="paragraph_style_1"><span style="line-height: 18px; " class="style">Checks Payable to:<br /></span></p>
                <p class="paragraph_style_1"><span style="line-height: 18px; " class="style">Squaw Dogs<br /></span></p>
                <p class="paragraph_style_1"><span style="line-height: 18px; " class="style">POB 3302<br /></span></p>
                <p class="paragraph_style_1"><span style="line-height: 18px; " class="style">Olympic Valley, CA 96146  <br /></span></p>
<%= render "layouts/footer" %>

app/views/avi/press.html.erb
<%= render "layouts/header" %>
<div class="container-fluid">
<h2 class="video">Articles</h2>
<div class="container"><%= image_tag "ap_logo.svg.png", class: "ap_logo" %>
<%= link_to "When an avalanche hits the slopes, let the dogs out", "http://bigstory.ap.org/article/bfdea282dcad4208ae68bbed9dedd511/when-avalanche-hits-slopes-let-dogs-out", class: "press_release" %>
</div>
<div class="container">
<%= image_tag "CNN_com.png", class: "cnn" %>
<%= link_to "Dogs audition to become heroes", "http://www.cnn.com/US/9901/29/dog.rescue/index.html", class: "press_release" %>
</div>
<h2 class="video">Video</h2>
<div class = "embed-container">
<%= embed("https://www.youtube.com/watch?v=MMfeBzCxBeA") %>
</div>

</div>


<%= render "layouts/footer" %>

app/views/dog/all_dogs.html.erb
<%= render 'layouts/header' %>

<div class="grid centered">
  <div class="grid-item grid-item--width2 grid-item--height2"><%= link_to murphy_path do %><%= image_tag "murphy.png", class: "w2h2" %><div class="dog_photo_name">Murphy and Eric</div><% end %></div>
  <div class="grid-item"><%= link_to boomer_path do %><%= image_tag "boomer_crop.png", class: "w1h1" %><div class="small_dog_photo_name">Boomer</div><% end %></div>
  <div class="grid-item"><%= link_to wylee_path do %><%= image_tag "wylee_crop.png", class: "w1h1" %><div class="small_dog_photo_name">Wylee</div><% end %></div>
  <div class="grid-item grid-item--width2 grid-item--height2"><%= link_to kaya_path do %><%= image_tag "Ben_and_Kaya.png", class: "w2h2" %><div class="dog_photo_name">Kaya and Ben</div><% end %></div>
  <div class="grid-item"><%= link_to shaka_path do %><%= image_tag "Shaka.png", class: "w1h1" %><div class="small_dog_photo_name">Shaka</div><% end %></div>
  <div class="grid-item"><%= link_to kaya_path do %><%= image_tag "kaya_crop.png", class: "w1h1" %><div class="small_dog_photo_name">Kaya</div><% end %></div>
   <div class="grid-item grid-item--width2 grid-item--heightless"><%= image_tag "avi_ed.png", class: "w2h1less" %></div>
    <div class="grid-item grid-item--width2 grid-item--height2"><%= link_to tucker_path do %><%= image_tag "york_and_tucker.png", class: "w2h2" %><div class="dog_photo_name">Tucker and Pete</div><% end %></div>
    <div class="grid-item"><%= link_to boon_path do %><%= image_tag "boon_crop.png", class: "w1h1" %><div class="small_dog_photo_name">Boon</div><% end %></div>
    <div class="grid-item"><%= link_to tucker_path do %><%= image_tag "tucker_card.jpg", class: "w1h1" %><div class="small_dog_photo_name">Tucker</div><% end %></div>
     <div class="grid-item grid-item--width2 grid-item--heightless"><%= image_tag "Squaw-Alpine-4cp-horz-stacked.png", class: "w2h1less" %></div>

  <div class="grid-item grid-item--width2 grid-item--height2"><%= link_to boomer_path do %><%= image_tag "boomer.png", class: "w2h2" %><div class="dog_photo_name">Boomer and Will</div><% end %></div>
<div class="grid-item"><%= link_to trooper_path do %><%= image_tag "trooper_dogs_crop.jpg",  class: "w1h1"%><div class="small_dog_photo_name">Trooper</div><% end %></div>
<div class="grid-item"><%= image_tag "dog-we-trust.jpg", class: "w1h1" %></div>
<div class="grid-item grid-item--width2 grid-item--height2"><%= link_to boon_path do %><%= image_tag "boon.png", class: "w2h2" %><div class="dog_photo_name">Boon and Erik</div><% end %></div>

  <div class="grid-item grid-item--width2 grid-item--height2"><%= image_tag "TeamSquawDog.jpg", class: "w2h2" %></div>
</div>

<%= render 'layouts/footer' %>

app/views/dog/boomer.html.erb
<%= render 'layouts/dog_card' %>
<%= render 'layouts/handler_image' %>
 <p style="padding-top: 0pt; " class="paragraph_style">Over the past 21 years Will has diligently worked in the ski industry ranging from being a founder in the Kinbasket Adventure Heli-tours in Revelstoke, BC to a professional Ski Patroller/Avalanche Forecaster and Avalanche Control, Explosives and Rescue Instructor for Squaw Valley, U.S.A. and a lead guide for Points North Heli Adventures in Cordova, Alaska. When Will is not working on skis, he spends his time developing avalanche safety gear.<br /></p>
                <p class="paragraph_style">Will earned a BS degree from the University of Vermont and has the following certifications: Level 3 Avalanche, American Mountain Guide Association, Level 1 Ski Guide, Alpine Skills International, Wilderness-EMT, California Blaster, All Mountain Ski Pro Instructor (AMSP). Will is also a member of the Canadian Avalanche Rescue Dog Association and a Certified dog Handler of Rasco with the Squaw Valley Ski Patrol, Olympic Valley, Ca.<br /></p>
                <p style="padding-bottom: 0pt; " class="paragraph_style_1">Other related experiences include: All types of climbing, skiing, and guiding, ranging from high-altitude alpine climbing in the Himalayas to high-level ski descents in Alaska and over 16 years of ski mountaineering throughout the High Sierra, Chugach, Cascades, Alaska Range, Tetons, Canadian and Colorado Rockies, Selkirks and Monashees, the White Mountains, and the French Alps.</p>
<%= render 'layouts/footer' %>

app/views/dog/boon.html.erb
<%= render 'layouts/dog_card' %>
<%= render 'layouts/handler_image' %>
  <p style="padding-top: 0pt; " class="paragraph_style">Erik Knudson Is a ski Patroller who started as a patroller at Killington, Vermont back in 1985. Since then Erik has called Squaw Valley home.  Squaw has given Erik the opportunity to work in Val D'isere, France.  First in 1992 as ski bum and later in 94/95  as a &quot;pisteuer&quot; patroller on exchange.  During his first visit to Val D’isere, he started the towns first avalanche beacon clinic for visiting tourist. A clinic he also started in Squaw Valley for visitors and locals a like.  Mount Buller, Australia has also hosted Erik on exchange.  Other work<br />related jobs include guiding in the promise land of AK. For Alaskan Backcountry Adventures and Chugach Powder Guides. <br /></p>
                <p class="paragraph_style"><br /></p>
                <p class="paragraph_style">Erik has been a pioneer in public service.  Founder of the “Snow Gods” an annual fundraising event that helps patrollers and public alike offset the costs of avalanche education through scholarships.  Hosting Squaw Valley’s first Avalanche Dog School and introducing CARDA to America.<br /></p>
                <p class="paragraph_style"><span class="style_1"><br /></span></p>
                <p class="paragraph_style">Erik’s dog is a ten year old long hair German Shepard from a Swiss Line.  She as attained a certification from the Swiss Alpine Club and has meet the Squaw Standard for many years.  This Big Black Dog is friendly and waiting for you to come up and say hi.<br /></p>
                <p style="padding-bottom: 0pt; " class="paragraph_style"> <br /></p>
<%= render 'layouts/footer' %>

app/views/dog/index.html.erb
<%= render 'layouts/header' %>
<div class="Team_dogs">

<%= image_tag 'dog_cover_crop.jpg', class:"img-responsive dogs" %>

</div>
<div class="container-fluid">
<h1>Dedicated to Avalanche Rescue and Education</h1>
<h4>With a special thanks to:</h4>
<%= image_tag "Squaw-Alpine-4cp-horz-stacked.png", id: "Squaw-Shield" %>
</div>
<div class="tainer">
<div class="box1">
<%= image_tag "EVH.jpg", class: "img-responsive", id:"EVH" %>
</div>
<div class="box2"><%= image_tag "cardalogo.png", class: " img-responsive", id:"cardalogo" %>
</div>
<div class="box3"><%= image_tag "Keoki.jpg", class: "img-responsive center-block", id: "Keoki"%>
</div>
</div>

        <div class="container paw"><span><h2><%= image_tag "paw_print.png", id:"Cross-logo" %>The Dogs <span class="glyphicon glyphicon-chevron-right"></span></h2></span>

        </div>
<div id="netflix">
<div id="row-pic">

    <div class="tile">
<div class="tile__media">
                <%= image_tag "wylee.png", class:"tile__img img-responsive" %>

      </div>
      <div class="tile__details">
        <div class="tile__title"><%=link_to "Wylee", wylee_path, class: "dog_name" %></div>
      </div><!-- tile__details -->
    </div><!-- tile -->



    <div class="tile">
<div class="tile__media">
        <%=image_tag "Ben_and_Kaya.png", class:"tile__img img-responsive"  %>
</div>
      <div class="tile__details">
        <div class="tile__title"><%=link_to "Kaya", kaya_path, class: "dog_name" %></div>
      </div><!-- tile__details -->
    </div><!-- tile -->



    <div class="tile">
<div class="tile__media">
       <%=image_tag "murphy.png", class:"tile__img img-responsive"  %>
</div>
      <div class="tile__details">
        <div class="tile__title"><%=link_to "Murphy", murphy_path, class: "dog_name" %></div>
      </div><!-- tile__details -->
    </div><!-- tile -->

      <div class="tile">
<div class="tile__media">
        <%=image_tag "shaka_close.jpg", class:"tile__img img-responsive"  %>
</div>
      <div class="tile__details">
        <div class="tile__title"><%=link_to "Shaka", shaka_path, class: "dog_name" %></div>
      </div><!-- tile__details -->
    </div><!-- tile -->



    <div class="tile">
<div class="tile__media">
        <%=image_tag "boomer.png", class:"tile__img img-responsive"  %>
</div>
      <div class="tile__details">
        <div class="tile__title"><%=link_to "Boomer", boomer_path, class: "dog_name" %></div>
      </div><!-- tile__details -->
    </div><!-- tile -->


    <div class="tile">
<div class="tile__media">
       <%=image_tag "boon.png", class:"tile__img img-responsive"  %>
</div>
      <div class="tile__details">
        <div class="tile__title"><%=link_to "Boon", boon_path, class: "dog_name" %></div>
      </div><!-- tile__details -->
    </div><!-- tile -->

          <div class="tile">
<div class="tile__media">
        <%=image_tag "trooper.jpg", class:"tile__img img-responsive", id: "trooper_netflix"  %>
        </div>
      <div class="tile__details">
        <div class="tile__title"><%=link_to "Trooper", trooper_path, class: "dog_name" %></div>
      </div><!-- tile__details -->
    </div><!-- tile -->


    <div class="tile">
<div class="tile__media">
       <%=image_tag "york_and_tucker.png", class:"tile__img"  %>
</div>
      <div class="tile__details">
        <div class="tile__title"><%=link_to "Tucker", tucker_path, class: "dog_name" %></div>
      </div><!-- tile__details -->
    </div><!-- tile -->
</div><!--  row-pic -->

</div>
 <div class="container paw"><span><h2>Where the Dogs at? </h2></span>
  </div>
<div id="map-container">
  <div id="map-canvas">

  </div>
</div>
<div id="legend">
    Legend
</div>


<%= render 'layouts/footer' %>
 <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['google_maps_api_key'] %>&callback=initMap"
        async defer></script>

app/views/dog/kaya.html.erb
<%= render 'layouts/dog_card' %>
<h2 class="video">Video</h2>
<div class = "embed-container">
<%= embed("https://www.youtube.com/watch?v=NiL_4YpQQrM") %>
</div>
<%= render 'layouts/handler_image' %>
<p style="padding-top: 0pt; " class="paragraph_style_1">Ben grew up in West Virginia skiing at Snowshoe Mountain before moving west after the completion of graduate school. He graduated from Marshall University with a BA in Sport Management and a MS in Exercise Physiology.<br /></p>
                <p class="paragraph_style_1"><br /></p>
                <p class="paragraph_style_1">With ten years in the ski industry, Ben started as a lift operator, before moving up to lift supervisor and bike patroller in Crested Butte, CO. He moved to Park City, UT in 2008 to begin his ski patrol career, and relocated to Truckee in 2011, joining Squaw Valley's ski patrol. <br /></p>
                <p class="paragraph_style_1"><br /></p>
                <p class="paragraph_style_1">An advocate for ongoing education, Ben seeks to improve his skills and knowledge through courses and certifications in snow science, K9 training, and emergency medicine. These include Level 1 &amp; 2 Avalanche, Outdoor Emergency Care specialist, American Heart Association CPR &amp; AED certification, California Blaster, Squaw Valley Avalanche Dog Handler, Placer County Search and Rescue team member, and Canadian Avalanche and Rescue Dog Association (CARDA) team member. Additionally, Ben and Kaya have attended two CARDA schools in Canada to train and hone their skills as a team.<br /></p>
                <p class="paragraph_style_1"><br /></p>
                <p class="paragraph_style_1">Ben is an avid outdoorsmen, who loves riding his mountain bike and playing soccer in the warmer months and skiing as much as possible in the winter. When not on his bike or skis, he also enjoys making his own hot sauce, barbecuing with friends and cheering on his favorite soccer clubs, Real Salt Lake, Liverpool, and the United States National Team. <br /></p>
                <p style="padding-bottom: 0pt; " class="paragraph_style_1">Ben lives in Truckee, CA with his wife Susan, a former professional ski patroller and instrumental figure in Kaya's training.</p>
<%= render 'layouts/footer' %>

app/views/dog/murphy.html.erb
<%= render 'layouts/dog_card' %>
<%= render 'layouts/handler_image' %>
<p style="padding-top: 0pt; " class="paragraph_style">Having been a member of the Squaw Valley Professional Ski Patrol for the past  20 plus years, Eric Seelenfreund is well qualified and experienced in avalanche control work and avalanche rescue. He is a supervisor for the crew and the high angle rescue team on top of being a dog handler. In addition to his winter skills, he also works during the summer months as a guide and teacher of rock climbing and mountaineering skills. <br /></p>
                <p class="paragraph_style"><br /></p>
                <p class="paragraph_style">Current certifications include: Emergency Medical Technician I, Outdoor Emergency Care Technician, American Heart Association CPR &amp; AED program and Level I &amp; II avalanche. He is licensed as a California Blaster and a member of Canadian Avalanche Rescue Dog Association.<br /></p>
                <p class="paragraph_style">    <br /></p>
                <p class="paragraph_style">As a 4th generation Squaw Valley Ski Patrol avalanche rescue dog, Murphy is currently mission ready for avalanche rescue and type I area wilderness searching.  Eric and Murphy are also members of the Placer County Search and Rescue Tahoe Dogs as well as members of YODOGS (Yosemite Search And Rescue dog team).<br /></p>
                <p class="paragraph_style"><br /></p>
                <p class="paragraph_style">Some other important experiences in Eric's life have been earning a BA from University of the Pacific. Working for Outward Bound of California, Tahoe Trips and Trails, North Tahoe Marina, No. Amer. Ski Training Center, and other organizations. Eric has climbed numerous routes in the High Sierras, Mt Shasta, and climbed Mt. Denali.<br /></p>
                <p class="paragraph_style"><br /></p>
                <p style="padding-bottom: 0pt; " class="paragraph_style">Eric lives in Truckee, CA with his wife, 3 daughters and Murphy. They all love skiing and the outdoor life which the Tahoe area provides.</p>
<%= render 'layouts/footer' %>

app/views/dog/shaka.html.erb
<%= render 'layouts/dog_card' %>
<%= render 'layouts/handler_image' %>
<h3>Coming Soon</h3>
<div class="spacer"></div>
<%= render 'layouts/footer' %>

app/views/layouts/_footer.html.erb
<div class="container" id="foot">
<footer class="footer">
<span class="follow">Follow us</span>
 <a href="https://www.instagram.com/squawdogs/" class="btn btn-social-icon btn-instagram">
    <span class="fa fa-instagram fa-2x"></span>
  </a>
   <a href="https://www.facebook.com/SquawDogs-181583001454/" class="btn btn-social-icon btn-facebook" >
    <span class="fa fa-facebook fa-2x"></span>
  </a>

    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>


</footer>
</div>

app/views/layouts/_header.html.erb
<header>

    <nav class="navbar navbar-fixed-top navbar-inverse">
      <div class="container-fluid" id="fluid-nav">


 <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">


      <span class="sr-only">Toggle navigation</span>

      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <div class="navbar-brand"><%= link_to root_path do %><%= image_tag "dog_logo.png", id: 'dog-logo' %></div>
    <% end %>
</div>

   <div id="navbar" class="navbar-collapse collapse">
    <ul class="nav navbar-nav pull-right">

                <li> <%= link_to "The Dogs", all_dogs_path %>
      </li>
      <li><%= link_to "Press", press_path %></li>
      <li>
                <%= link_to "Avalanche Education", avi_path %>
              </li>

              <li><%= link_to "Donate", donate_path %></li>

              <li class="divider"></li>
              <li>
                <%= link_to "Home", root_path %>
              </li>

             </ul>
           </div><!-- navbar-collapse -->
</div>
</nav>
</header>









</header>